# Generated by Django 4.2.7 on 2023-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=50),
        ),
    ]
