# Generated by Django 4.2.7 on 2023-11-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booktable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
